import Head from "next/head";
import { Inter } from "next/font/google";
import GetSupport from "../components/GetSupport/GetSupport";

export default function Home() {
  return (
    <>
      <Head>
        <title> cloud ready</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <GetSupport />
      </main>
    </>
  );
}

